server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: tags-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/tags/**
          filters:
            - RewritePath=/api/v1/tags/(?<segment>.*), /$\{segment}
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 60000
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 200000
  jpa:
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

